# 0.0 Codes for import/reload modules, timing

## timing

In [1]:
import time, datetime
start_time = time.time()
print("--- time taken for michel: %s ---" % (str(datetime.timedelta(seconds=time.time() - start_time))))

--- time taken for michel: 0:00:00.000047 ---


# insert custom library paths

In [1]:
import sys
# https://stackoverflow.com/questions/4383571/importing-files-from-different-folder
# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1,'./02_positron_sampling')
sys.path

['/lustre/collider/junkai.ng/hybridMC',
 './02_positron_sampling',
 '/home/junkai.ng/.conda/envs/root_py38/lib/python38.zip',
 '/home/junkai.ng/.conda/envs/root_py38/lib/python3.8',
 '/home/junkai.ng/.conda/envs/root_py38/lib/python3.8/lib-dynload',
 '',
 '/home/junkai.ng/.conda/envs/root_py38/lib/python3.8/site-packages',
 '/home/junkai.ng/.conda/envs/root_py38/lib/python3.8/site-packages/IPython/extensions',
 '/home/junkai.ng/.ipython']

## import and reload libraries, functions

In [2]:
import PositronDecay

Welcome to JupyROOT 6.24/00


In [ ]:
import importlib
importlib.reload(PositronDecay)

In [14]:
# reload from xxx import zzz
importlib.reload(sys.modules['PositronDecay'])
from PositronDecay import GenerateMichelKinematics, GeneratePositron_MRF, Calculate_Phase, GeneratePositron_LAB

In [4]:
# numpy vectorize
def f(x):
    return x * np.array([1,1,1,1,1], dtype=np.float32)
g = np.vectorize(f, otypes=[np.ndarray])
a = np.arange(4)
print(g(a))

[array([0., 0., 0., 0., 0.], dtype=float32)
 array([1., 1., 1., 1., 1.], dtype=float32)
 array([2., 2., 2., 2., 2.], dtype=float32)
 array([3., 3., 3., 3., 3.], dtype=float32)]
